### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JLCareglio** [justaCasualCoder/Zoneminder-Termux#1]
**Describe the bug**
input:
```
curl -sSL "https://raw.githubusercontent.com/justaCasualCoder/Zoneminder-Termux/main/installzm.sh" | bash
```
output:
```
Which version of ZM do you want to use? [1.34 or 1.36]: bash: line 44: syntax error near unexpected token `)'
bash: line 44: `    1.34)'
```

**To Reproduce**
1. Donwload [Termux](https://f-droid.org/en/packages/com.termux/)
2. Set up a proot container 
```
termux-setup-storage
proot-distro install debian
```
3. Login to the container
```
proot-distro login debian
```
4. Install Zoneminder!
```
curl -sSL "https://raw.githubusercontent.com/justaCasualCoder/Zoneminder-Termux/main/installzm.sh" | bash
```

**Expected behavior**
¯\_( ͡° ͜ʖ ͡°)_/¯

**Device Info**
OS: Android 10 armv8l
Kernel: 4.9.170
Shell: zsh 5.9
CPU: ARMv8 rev 4 (v8l) (4) @ 1.296GHz
Memory: 608MiB / 1976MiB

**proot-distro info**
OS: Debian GNU/Linux 12 (bookworm) armv8l
Kernel: 6.2.1-PRoot-Distro
Shell: bash 5.2.15
CPU: ARMv8 rev 4 (v8l) (4) @ 1.296GHz
Memory: 614MiB / 1976MiB

**Comment by justaCasualCoder** [comment]
Please try running this: 
```bash
wget https://raw.githubusercontent.com/justaCasualCoder/Zoneminder-Termux/main/installzm.sh && bash installzm.sh
```
I have not updated it in a while, later today I will take a look at the code.

Thanks for reporting the bug!
